export type Challenge = {
  id: number
  category: string
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  {
    id: 1,
    category: "Países",
    word: "Brasil",
    tip: "Maior país da América do Sul.",
  },
  {
    id: 2,
    category: "Países",
    word: "Portugal",
    tip: "Famoso pelos azulejos e pelo Fado.",
  },
  { id: 3, category: "Países", word: "França", tip: "País da Torre Eiffel." },
  { id: 4, category: "Países", word: "Japão", tip: "Terra do sol nascente." },
  {
    id: 5,
    category: "Países",
    word: "Alemanha",
    tip: "Famoso por suas cervejas e Oktoberfest.",
  },
  {
    id: 6,
    category: "Países",
    word: "Itália",
    tip: "Berço do Império Romano.",
  },
  {
    id: 7,
    category: "Países",
    word: "Espanha",
    tip: "País do flamenco e das touradas.",
  },
  {
    id: 8,
    category: "Países",
    word: "Argentina",
    tip: "Terra do tango e de Maradona.",
  },
  {
    id: 9,
    category: "Países",
    word: "México",
    tip: "Famoso por tacos e mariachis.",
  },
  {
    id: 10,
    category: "Países",
    word: "Austrália",
    tip: "Casa dos cangurus e coalas.",
  },
  {
    id: 11,
    category: "Países",
    word: "Egito",
    tip: "Famoso por suas pirâmides.",
  },
  { id: 12, category: "Países", word: "Canadá", tip: "País do maple syrup." },
  { id: 13, category: "Países", word: "Rússia", tip: "Maior país do mundo." },
  { id: 14, category: "Países", word: "Índia", tip: "Famosa pelo Taj Mahal." },
  { id: 15, category: "Países", word: "China", tip: "Casa da Grande Muralha." },
  {
    id: 16,
    category: "Países",
    word: "Inglaterra",
    tip: "Berço do futebol moderno.",
  },
  { id: 17, category: "Países", word: "Grécia", tip: "Origem das Olimpíadas." },
  {
    id: 18,
    category: "Países",
    word: "Turquia",
    tip: "Onde Europa encontra a Ásia.",
  },
  {
    id: 19,
    category: "Países",
    word: "Chile",
    tip: "País estreito da América do Sul.",
  },
  {
    id: 20,
    category: "Países",
    word: "Colômbia",
    tip: "Famosa pelo café e esmeraldas.",
  },
  { id: 21, category: "Países", word: "Peru", tip: "Lar de Machu Picchu." },
  {
    id: 22,
    category: "Países",
    word: "Coreia",
    tip: "Dividido em Norte e Sul.",
  },
  { id: 23, category: "Países", word: "Noruega", tip: "Terra dos fiordes." },
  {
    id: 24,
    category: "Países",
    word: "Suíça",
    tip: "Famosa por chocolates e relógios.",
  },
  {
    id: 25,
    category: "Países",
    word: "África do Sul",
    tip: "País do safári e Nelson Mandela.",
  },
  {
    id: 26,
    category: "Países",
    word: "Vietnã",
    tip: "Famoso por sua culinária e guerra.",
  },
  {
    id: 27,
    category: "Países",
    word: "Indonésia",
    tip: "Maior arquipélago do mundo.",
  },
  {
    id: 28,
    category: "Países",
    word: "Nigéria",
    tip: "País mais populoso da África.",
  },
  {
    id: 29,
    category: "Países",
    word: "Nova Zelândia",
    tip: "Terra dos hobbits e kiwi.",
  },
  {
    id: 30,
    category: "Países",
    word: "Polônia",
    tip: "Berço de Chopin e Marie Curie.",
  },
  {
    id: 31,
    category: "Países",
    word: "Holanda",
    tip: "Famosa por tulipas e moinhos.",
  },
  {
    id: 32,
    category: "Animais",
    word: "Elefante",
    tip: "Maior mamífero terrestre.",
  },
  {
    id: 33,
    category: "Animais",
    word: "Tigre",
    tip: "Felino listrado e feroz.",
  },
  {
    id: 34,
    category: "Animais",
    word: "Golfinho",
    tip: "Mamífero aquático inteligente.",
  },
  {
    id: 35,
    category: "Animais",
    word: "Cavalo",
    tip: "Animal usado em corridas.",
  },
  {
    id: 36,
    category: "Animais",
    word: "Jacaré",
    tip: "Réptil com dentes afiados.",
  },
  { id: 37, category: "Animais", word: "Coruja", tip: "Símbolo de sabedoria." },
  {
    id: 38,
    category: "Animais",
    word: "Pinguim",
    tip: "Ave que não voa, mas nada.",
  },
  {
    id: 39,
    category: "Animais",
    word: "Lobo",
    tip: "Parente selvagem do cachorro.",
  },
  {
    id: 40,
    category: "Animais",
    word: "Camelo",
    tip: "Tem corcovas para armazenar água.",
  },
  {
    id: 41,
    category: "Animais",
    word: "Águia",
    tip: "Ave de rapina poderosa.",
  },

  {
    id: 42,
    category: "Filmes",
    word: "Titanic",
    tip: "Romance no navio que afundou.",
  },
  {
    id: 43,
    category: "Filmes",
    word: "Avatar",
    tip: "Ficção científica em Pandora.",
  },
  {
    id: 44,
    category: "Filmes",
    word: "Matrix",
    tip: "Neo descobre a verdade.",
  },
  {
    id: 45,
    category: "Filmes",
    word: "Vingadores",
    tip: "Heróis enfrentam Thanos.",
  },
  {
    id: 46,
    category: "Filmes",
    word: "Coringa",
    tip: "Explora a origem de um vilão.",
  },
  {
    id: 47,
    category: "Filmes",
    word: "Shrek",
    tip: "Ogro que vive em um pântano.",
  },
  {
    id: 48,
    category: "Filmes",
    word: "Frozen",
    tip: "Rainha do gelo e sua irmã.",
  },
  {
    id: 49,
    category: "Filmes",
    word: "Harry Potter",
    tip: "O menino que sobreviveu.",
  },
  {
    id: 50,
    category: "Filmes",
    word: "Star Wars",
    tip: "Saga de Jedis e Siths.",
  },
  {
    id: 51,
    category: "Filmes",
    word: "Homem-Aranha",
    tip: "Herói que escala paredes.",
  },

  {
    id: 52,
    category: "Comidas",
    word: "Pizza",
    tip: "Massa italiana com recheios variados.",
  },
  {
    id: 53,
    category: "Comidas",
    word: "Sushi",
    tip: "Prato japonês com arroz e peixe.",
  },
  {
    id: 54,
    category: "Comidas",
    word: "Hambúrguer",
    tip: "Sanduíche com carne e pão.",
  },
  {
    id: 55,
    category: "Comidas",
    word: "Lasagna",
    tip: "Prato italiano com camadas.",
  },
  {
    id: 56,
    category: "Comidas",
    word: "Feijoada",
    tip: "Prato brasileiro com feijão preto.",
  },
  {
    id: 57,
    category: "Comidas",
    word: "Churrasco",
    tip: "Carne assada na brasa.",
  },
  {
    id: 58,
    category: "Comidas",
    word: "Tacos",
    tip: "Prato típico do México.",
  },
  {
    id: 59,
    category: "Comidas",
    word: "Sopa",
    tip: "Líquido quente e nutritivo.",
  },
  {
    id: 60,
    category: "Comidas",
    word: "Chocolate",
    tip: "Doce feito de cacau.",
  },
  {
    id: 61,
    category: "Comidas",
    word: "Sorvete",
    tip: "Sobremesa gelada e doce.",
  },

  {
    id: 62,
    category: "Esportes",
    word: "Futebol",
    tip: "Jogo com bola e 11 jogadores.",
  },
  {
    id: 63,
    category: "Esportes",
    word: "Basquete",
    tip: "Jogo com cestas e arremessos.",
  },
  {
    id: 64,
    category: "Esportes",
    word: "Tênis",
    tip: "Jogo com raquetes e rede.",
  },
  { id: 65, category: "Esportes", word: "Vôlei", tip: "Jogo com rede e bola." },
  {
    id: 66,
    category: "Esportes",
    word: "Natação",
    tip: "Competição dentro da água.",
  },
  {
    id: 67,
    category: "Esportes",
    word: "Atletismo",
    tip: "Corrida, salto e arremesso.",
  },
  {
    id: 68,
    category: "Esportes",
    word: "Boxe",
    tip: "Luta com luvas no ringue.",
  },
  { id: 69, category: "Esportes", word: "Rúgbi", tip: "Jogo com bola oval." },
  {
    id: 70,
    category: "Esportes",
    word: "Golfe",
    tip: "Jogo com taco e buracos.",
  },
  {
    id: 71,
    category: "Esportes",
    word: "Ciclismo",
    tip: "Corrida com bicicletas.",
  },

  {
    id: 72,
    category: "Tecnologia",
    word: "Computador",
    tip: "Máquina usada para programar.",
  },
  {
    id: 73,
    category: "Tecnologia",
    word: "Smartphone",
    tip: "Dispositivo de comunicação móvel.",
  },
  {
    id: 74,
    category: "Tecnologia",
    word: "Internet",
    tip: "Rede que conecta o mundo.",
  },
  {
    id: 75,
    category: "Tecnologia",
    word: "Robô",
    tip: "Máquina que pode se mover.",
  },
  {
    id: 76,
    category: "Tecnologia",
    word: "Drones",
    tip: "Veículos voadores controlados remotamente.",
  },
  {
    id: 77,
    category: "Tecnologia",
    word: "Blockchain",
    tip: "Tecnologia usada no Bitcoin.",
  },
  {
    id: 78,
    category: "Tecnologia",
    word: "Chatbot",
    tip: "Assistente virtual em textos.",
  },
  {
    id: 79,
    category: "Tecnologia",
    word: "Inteligência Artificial",
    tip: "Máquinas que pensam como humanos.",
  },
  {
    id: 80,
    category: "Tecnologia",
    word: "Servidor",
    tip: "Computador que armazena dados online.",
  },
  {
    id: 81,
    category: "Tecnologia",
    word: "Algoritmo",
    tip: "Conjunto de regras para resolver problemas.",
  },

  {
    id: 82,
    category: "Personagens",
    word: "Batman",
    tip: "Herói sem poderes de Gotham.",
  },
  {
    id: 83,
    category: "Personagens",
    word: "Homem de Ferro",
    tip: "Bilionário em armadura tecnológica.",
  },
  {
    id: 84,
    category: "Personagens",
    word: "Mickey Mouse",
    tip: "Rato famoso da Disney.",
  },
  {
    id: 85,
    category: "Personagens",
    word: "Superman",
    tip: "Alienígena com capa vermelha.",
  },
  {
    id: 86,
    category: "Personagens",
    word: "Sonic",
    tip: "O ouriço azul veloz.",
  },
  {
    id: 87,
    category: "Personagens",
    word: "Mario",
    tip: "Encanador que salva a princesa.",
  },
  {
    id: 88,
    category: "Personagens",
    word: "Hulk",
    tip: "Gigante verde com muita força.",
  },
  {
    id: 89,
    category: "Personagens",
    word: "Goku",
    tip: "Guerreiro Saiyajin de Dragon Ball.",
  },
  {
    id: 90,
    category: "Personagens",
    word: "Elsa",
    tip: "Rainha do gelo em Frozen.",
  },
  {
    id: 91,
    category: "Personagens",
    word: "Pikachu",
    tip: "Mascote elétrico de Pokémon.",
  },
]
